### ISSUE TITLE
! Navigation_bar: обновить панель навигации

### ISSUE THREAD

**Issue by roscherk** [spbu-math-cs/zakroma#18]
Обсудить новые и старые вкладки, изменить "Настройки" на "Профиль".

Скорее всего, количество вкладок увеличится до 5 (вместо 3).
Возможные вкладки: главная, холодильник, маркет, рационы, профиль.

**Comment by DmGvozd** [comment]
![Image](https://github.com/spbu-math-cs/zakroma/assets/112868029/4a584e14-a9ca-49be-a004-69b56149eb8b)
