### ISSUE TITLE
Store: нарисовать макет экрана в Figma

### ISSUE THREAD

**Issue by DmGvozd** [spbu-math-cs/zakroma#24]

**Comment by DmGvozd** [comment]
![Image](https://github.com/spbu-math-cs/zakroma/assets/112868029/dab89a30-0be5-43a1-b01c-1907a82d3a71)

**Comment by roscherk** [comment]
1. Как мы от 144 переходим к 145?
2. Правильно ли я понял, что 145 — это вариант на случай, когда у пользователя нет семейной группы, а 146-147 — когда есть?
3. Где-то должна быть кнопка для контекстного меню — хотя я пока хз, что туда можно добавить кроме массовых операций — можно накидать идей на созвоне, а можно просто добавить массовый выбор по аналогии с ios/андроидом
4. Что появляется (или куда попадаем) при нажатии на +? Опция добавления продуктов из чека где-то там будет?
5. Спорный момент, но мне кажется, что кнопки редактирования (плюс, минус, удалить) надо спрятать при первом заходе на экран и показать при переходе в режим редактирования, чтобы исключить случайные нажатия. 
Мотивация: при наивной реализации мы в ответ на каждое нажатие отправляем на сервер запрос вида «увеличь кол-во продукта N на 1» — это накладно.
Впрочем, можно сделать случайные нажатия бесплатными: не отправлять запросы на бэк, пока пользователь остаётся на этом экране. Когда же выходим с экрана, если есть изменения, спрашиваем: сохранить их? Если да, то только в этот момент отправляем всю пачку запросов. Это как-то реализуется, но наверное не так легко, как наивный вариант.

**Comment by DmGvozd** [comment]
1. никак, это разные варианты одного экрана
2. 146-147 - это вообще иное представление холодильника (вариант 3)
3. в ios она находится выше названия обычно (прям надо холодильником). для этого такой отступ обычно и делается. в случае с роботом - хз
4. да. поиск уже был ранее нарисован на 114 экране. к тому же, можно туда скан qr запихнуть. просто при нажатии на плюс разворачиваем его в два пункта меню и даем пользователю на выбор либо скан, либо добавление вручную 
5. просто сделать кнопку контекстного меню "редактировать", мэн... 
кнопки нарисованы так, как они будут в режиме редактирования. удалить всегда можно успеть.

**Comment by DmGvozd** [comment]
поповоду второго: либо делаем так, как 146-147, либо как 144/145. кнопка маркета хз вообще нужна или нет, не особо понимаю зачем, но с другой стороны понимаю

**Comment by roscherk** [comment]
> 3\. в ios она находится выше названия обычно (прям надо холодильником)

Нарисуешь?

**Comment by DmGvozd** [comment]
![Image](https://github.com/spbu-math-cs/zakroma/assets/112868029/5284b768-015d-4c05-b3f9-a005b17b9a39)

**Comment by DmGvozd** [comment]
на самом деле на макете она выглядит несуразно, но на экране телефона так вообще не кажется

в любом случае, нам в первую очередь нужен функционал, а придумать куда ее засунуть в другое место пока не оч удается

по поводу навигационной панели - вообще отдельная тема. так как мы туда планируем засовывать 5 кнопок вместо 3, тема с заменой настроек на многофункциональную кнопку опций уже не катит
